spring:
  application:
    name: findex
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  config:
    import: "optional:.env"


  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

index-api:
  service-key: ${API_KEY}

app:
  schedule:
    auto-sync-cron: ${AUTO_SYNC_CRON}